# Generated by Django 2.2.3 on 2019-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='static/karly/%Y/%m/%d')),
                ('bio', models.TextField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Amber',
        ),
        migrations.DeleteModel(
            name='Karly',
        ),
    ]
