# Generated by Django 2.2.3 on 2019-07-22 22:28

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190722_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.FileField(upload_to=pages.models.generate_filename)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=4000)),
            ],
        ),
    ]
