# Generated by Django 2.2.3 on 2019-07-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
