# Generated by Django 2.2.3 on 2019-07-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_homepage_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.ImageField(upload_to='images/hosts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile',
            field=models.ImageField(upload_to='images/karly/%Y/%m/%d'),
        ),
    ]
